### ISSUE TITLE
Make the addition of message types dynamic

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterpartyd#194]
Some propositions to : 
1) lighten the main file
2) not to be obliged to change counterpartyd.py when we add transaction (like #193)

- put in json file all the arguments list, with explanation and generate dynamically this block of code:
https://github.com/CounterpartyXCP/counterpartyd/blob/master/counterpartyd.py#L535-L695
And also generate dynamically this block:
https://github.com/CounterpartyXCP/counterpartyd/blob/master/counterpartyd.py#L763-L985
this json file can be also used to generate a basic documentation.

- in config file add default values for all config variables, and as possible make dynamic set_options()

- move functions that can be useful for the API in utils.py or api.py. For instance get_address() could be also an api function (in fact there is almost the same function rewritten in counterblockd). Also all the viewing function should be api functions and counterpartyd.py just format the results.

**Comment by adamkrellenstein** [comment]
Closing this given its age.
