### ISSUE TITLE
`util.holders(db, asset)` is slow

### ISSUE THREAD

**Issue by mcelrath** [CounterpartyXCP/counterpartyd#250]
Dogeparty has now issued more than 9000 assets, and has a 1 minute block time, so is consuming a lot more CPU than Counterparty running on BTC (about 36% CPU utilization on average).  I profiled it and found that over 80% of this CPU time is taken up in `util.holders(db, asset)` at `lib/util.py:631`.  This may become a limiting factor as Counterparty grows.

Can the performance of this function be improved by the addition of the right indices?

**Comment by adamkrellenstein** [comment]
The only thing left to do is #347.
