### ISSUE TITLE
Add `escrowed` field in `balances` table

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterpartyd#347]
With this field we can avoid all these queries in `util.holders` and replace them by only one like this `SELECT address FROM balances WHERE asset='XXXX' AND (quantity > 0 OR escrowed > 0)`.
This can be done, for instance, by adding 2 boolean parameters in `util.credit` and `util.debit` functions: `from_escrow` and `to_escrow`

**Comment by adamkrellenstein** [comment]
After some discussion, this is not the right way to go about this.
