### ISSUE TITLE
automatic redemption of multi-sig outputs

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterpartyd#415]
Mentioned here: #414

**Comment by adamkrellenstein** [comment]
Our transaction volume is getting large enough that it's probably worth putting the time into making this happen sooner rather than later.

@ouziel-slama, can you put some thought into this?

**Comment by ouziel-slama** [comment]
We need to change the condition [here](https://github.com/CounterpartyXCP/counterpartyd/blob/develop/counterpartylib/lib/backend/__init__.py#L129) by something like: 
`if can_be_spent(vout, source):` 
(@adamkrellenstein, I'am sure you can find a better name for this method ;-))
The difference is when `source` is monosig and `scriptpubkey['hex']` is multisig.
In this case, I think that `can_be_spent()` should return `True` if:
- the vout is a multisig 1 of 3
- one of those 3 addresses is the `source`
- the amount is equal to MULTISIG_DUST

**Comment by adamkrellenstein** [comment]
@ouziel-slama, this is what I have now. Haven't tested it, but what do you think?
```                                                             
def is_vout_spendable(vout, source):                                              
    source = script.make_canonical(source)                                      
    scriptpubkey_hex = vout['scriptpubkey']['hex']                              
    c_scriptpubkey = bitcoinlib.core.CScript(bitcoinlib.core.x(scriptpubkey_hex))
    vout_address = script.scriptpubkey_to_address(c_scriptpubkey)               
    if not script.is_multisig(vout_address):                                    
        if vout_address == source:                                              
            return True                                                         
    else:                                                                       
        signatures_required, pubkeyhashes, signatures_possible = script.extract_array(vout_address)                      
        if signatures_required == 1 and source in pubkeyhashes:                 
            return True                                                            
    return False                                       
```

**Comment by ouziel-slama** [comment]
looks good! just if we don't check the value, I think we need to use in priority outputs with a dust value.

**Comment by adamkrellenstein** [comment]
Solved.
