### ISSUE TITLE
Integrate with VerSum? [bounty]

### ISSUE THREAD

**Issue by ELBQ** [CounterpartyXCP/counterpartyd#426]
**Background for Non-Technical Users**

VerSum makes up for the lack of [SPV support](https://blog.ethereum.org/2014/11/13/scalability-part-3-metacoin-history-multichain/) in Counterparty. VerSum neutralizes arguments against Counterparty that live or die on Counterparty's lack of SPV support. With VerSum integration, serious criticisms thrown at Counterparty like this:

> The advantage of a metacoin protocol is that it can allow for more advanced transaction types, including custom currencies, decentralized exchange, derivatives, etc, that are impossible on top of Bitcoin itself. However, metacoins on top of Bitcoin have one major flaw: simplified payment verification, already difficult with colored coins, is outright impossible on a metacoin. The reason is that while one can use SPV to determine that there is a transaction sending 30 metacoins to address X, that by itself does not mean that address X has 30 metacoins; what if the sender of the transaction did not have 30 metacoins to start with and so the transaction is invalid? Finding out any part of the current state essentially requires scanning through all transactions going back to the metacoin’s original launch to figure out which transactions are valid and which ones are not. This makes it impossible to have a truly secure client without downloading the entire 12 GB Bitcoin blockchain.

become null and void. Counterparty needs VerSum especially so now that smart contracts are playing a larger role in its ecosystem. Please give the [whitepaper](http://people.csail.mit.edu/nickolai/papers/vandenhooff-versum.pdf) a read if you haven't already.

-------------------

[VerSum](http://people.csail.mit.edu/nickolai/papers/vandenhooff-versum.pdf) ensures the accuracy and completeness of federated return data, regardless of datatype, with minimal client overhead.

> VerSum is a refereed delegation of computation, or RDoC, system. A VerSum client outsources a computation to a pool of independent servers, and can determine the correct result as long as it can reach one honest server. To handle large inputs, outputs, and intermediate state, VerSum stores all data in authenticated data structures.

VerSum guarantees that data returned to lightweight clients from remote servers is authentic and complete if just *one* server of many federated servers is honest. It was designed in part to obsolete the need for SPV in Namecoin, and the authors claim limited success in testing.

I can't stress the importance of VerSum integration enough. If you want secure lightweight Counterparty clients complete with smart contract support, you really need VerSum. VerSum is absolutely instrumental to the healthy growth of Counterparty.

I will pledge 125 XCP towards this goal, because I believe VerSum benefits every Counterparty user.

**Comment by adamkrellenstein** [comment]
Closing because 'integration' isn't well defined.
