### ISSUE TITLE
Change blockchain-service-name default to addrindex?

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterpartyd#572]
I wonder if the default value for `blockchain-service-name` could be changed to `addrindex` instead of `jmcorgan` to better reflect interdependency between `addrindex=1` in `bitcoin.conf` and what's used in `blockchain-service-name` in `counterpartyd.conf`. 

Code could permit either of the parameters to be used.

**Comment by adamkrellenstein** [comment]
We're just going to get rid of everything but `addrindex`, so the option will go away.
