### ISSUE TITLE
Use `old_rpc()` for all RPC calls

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterpartyd#588]
`old_rpc()` uses `requests` and is thread safe.
In the code of `python-bitcoinlib` rpc module, I don't see any reason to use it.
The only important thing IMHO is to deserialise transactions with `python-bitcoinlib`, like is done here: https://github.com/petertodd/python-bitcoinlib/blob/master/bitcoin/rpc.py#L313.
But we are already doing that with `old_rpc()` in the most important place: https://github.com/CounterpartyXCP/counterpartyd/blob/master/lib/blocks.py#L482.

**Comment by petertodd** [comment]
FWIW the REST API is adding things like chain height: https://github.com/bitcoin/bitcoin/pull/5548

So long as python-bitcoinlib is being used for parsing I see no reason why you couldn't use the old RPC code; it shouldn't matter how the data gets to the underlying parsing code. My thinking re the RPC in python-bitcoinlib is to keep it simple, and if someone has less simple needs by all means they should use something else.

**Comment by adamkrellenstein** [comment]
Great. Thanks @petertodd.

ACK, then.
