### ISSUE TITLE
counterparty-cli.py: set_up() got an unexpected keyword argument 'logfile'

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterpartyd#592]
* v9.49.3 with changed `counterparty-cli.py` (based on fix in #591)
* I downloaded the newest version of the file and replaced the old one. I'm not sure if I should clone the entire `develop` branch instead. When I run it with the `master` version, I get the same error as in #591. I think the bug may have been introduced later because the Jan 1 commit also has this issue.

```
C:\Windows\system32>python c:\counterpartyd_build\dist\counterpartyd\counterpart
y-cli.py --testnet --data-dir c:\bitcoin-core-0.10\counterparty-testnet --config
-file c:\bitcoin-core-0.10\TESTNET.counterpartyd.conf market
Traceback (most recent call last):
  File "c:\counterpartyd_build\dist\counterpartyd\counterparty-cli.py", line 736
, in <module>
    testcoin=args.testcoin)
  File "c:\counterpartyd_build\dist\counterpartyd\counterparty-cli.py", line 261
, in set_options
    log.set_up(args, logfile=False)
TypeError: set_up() got an unexpected keyword argument 'logfile'
```

**Comment by adamkrellenstein** [comment]
You need to clone the whole thing.

**Comment by rippler** [comment]
Good, confirmed to work with `develop`..
