### ISSUE TITLE
Move from SQLite3 (apsw) to LevelDB (plyvel)?

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterpartyd#594]
A quick-and-dirty implementation apparently allowed for three-second reparses. 8-)

Of course, this would be a **major** change.

Alternative: SQLite4 implements a key/value store which is apparently even faster than LevelDB?? See https://sqlite.org/src4/doc/trunk/www/design.wiki

**Comment by rippler** [comment]
I've had several problems with LevelDB (used by `bitcoin core`) on the ARM platform. While seemingly unimportant, it may matter should this thing need to run on embedded (kiosks, mobile phones, etc.) one day. Possibly interesting: SQLite4 does all numeric computations using decimal arithmetic.
Since I value stability/resistance to corruption more than performance, I vote for whichever is more stable! :-)

**Comment by mtbitcoin** [comment]
Are there any considerations for moving to a server based system such as MySQL ?

**Comment by ouziel-slama** [comment]
I like the idea to use a key/value database. Not sure if Sqlite4 is enough mature, but seems very interesting.
IMHO the ideal is to let the users pick the database he wants, and give to developers an easy way to implement a wrapper for any database. We "just" need to isolate all SQL queries in functions in a specific modules.

**Comment by rippler** [comment]
@ouziel-slama, a wrapper would be ideal. Key-value: since we already use mongo in Fed Node, a wrapper would make it possible to leverage mongo.

**Comment by adamkrellenstein** [comment]
When would it make sense for two different users to use two different databases? Not worth the effort to support multiple ones IMHO.

**Comment by mtbitcoin** [comment]
@adamkrellenstein   I can see a need for multiple users to single database but not for two different databases

**Comment by raph** [comment]
RocksDB might be a better choice considering the db will get pretty big over time

**Comment by ouziel-slama** [comment]
I agree with @mtbitcoin here.
IMHO for future light wallet it's very important to make `counterparty-lib` usable as a web server very easily. The goal is to make easy to everyone to create scalable services like this https://blockchain.info/api/json_rpc_api but for Counterparty API, or services like Blockscan and even like Counterwallet.
In short for desktop applications `sqlite` or `leveldb` are perfect, for web applications `mysql` or `mongodb` are much more adapted, and ideally `counterparty-lib` should be usable for web and desktop applications.

**Comment by mtbitcoin** [comment]
For pure reads only (and with some caching) SQLite works quite fine. But you start to run into issues the moments there are ongoing write (locks) and also attempting to perform reads. I think the performance differences from migrating SQLite to another file based database like level DB is negligible, as there are tradeoffs between both products.  

If the decision to move to another DB is to be made, I'd say making the jump to a full client/server db (i.e MySQL, mongo, etc) solution will negate any future performance issues that might arise from the DB type

**Comment by atweiden** [comment]
[electrum-server](https://github.com/spesmilo/electrum-server) uses leveldb+plyvel. There are APIs that rely on polling electrum-server instances. Not sure if anyone runs electrum-server on Raspberry Pi.

**Comment by adamkrellenstein** [comment]
Thought a lot about this. An RMDBS is safer, and should scale fine.
