### ISSUE TITLE
Update API to Ignore Asset Callability

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterpartyd#614]

**Comment by deweller** [comment]
I am unable to issue additional units of a token I created a long time ago called DWLTBCTEST.

Counterpartyd returns the error "cannot change callability".

I was unable to issue additional units through the API or using counterwallet.io.

This isn't an urgent issue for me, but I wanted to add it here for reference.

**Comment by adamkrellenstein** [comment]
@deweller: that's a separate bug. #616
