### ISSUE TITLE
Cannot Change Callability

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterpartyd#616]
@deweller reported:

> I am unable to issue additional units of a token I created a long time ago called DWLTBCTEST.

> Counterpartyd returns the error "cannot change callability".

> I was unable to issue additional DWLTBCTEST neither by calling counterpartyd (9.94.3) nor by using counterwallet.io.

> This isn't an urgent issue for me, but I wanted to add it here for reference.

**Comment by adamkrellenstein** [comment]
@deweller, this is through the CLI or API?

**Comment by deweller** [comment]
I used the API.

**Comment by adamkrellenstein** [comment]
Solved.
