### ISSUE TITLE
Merkle trees? How does Counterparty work with light clients?

### ISSUE THREAD

**Issue by SouKw** [CounterpartyXCP/counterpartyd#618]
I read this https://blog.ethereum.org/2015/01/10/light-clients-proof-stake/, but the Counterparty docs don't discuss this.

> Ethereum extends this basic mechanism with a two additional Merkle trees in each block header, allowing nodes to prove not just that a particular transaction occurred, but also that a particular account has a particular balance and state, that a particular event occurred, and even that a particular account does not exist.

Can Counterparty provide similar merkle proofs to Ethereum?

**Comment by goodtaster** [comment]
Ethereum uses its own blockchain. For XCP, this an open question (since Counterparty uses the Bitcoin blockchain and cannot change that.)

 But here is one proposal (with an unverified 125xcp bounty): #426

**Comment by adamkrellenstein** [comment]
Going to close this issue and discuss only specific technical proposals on GitHub (more discussion should be moved to the forums).
