### ISSUE TITLE
Global `Server DB` variable?

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterpartyd#622]
So we don't have to pass around `db`...

This should only work for the functions that aren't used by the API server.

**Comment by ouziel-slama** [comment]
hum..I'am really hesitant about this one. Seems to me much more complicated than the block index..
I feel like the only clean way to avoid the `db` parameter is to move to OOP style..
or maybe we can make it optional with a default value. For instance `f(db, a, b)` become `f(a, b, db=config.DB)`?

**Comment by adamkrellenstein** [comment]
Why the hesitancy? What's the risk? I don't see any potential consensus issues at all. The only risk is mixing read-only and read-write connections accidentally, no?

**Comment by ouziel-slama** [comment]
Yes, I agree there is no potential consensus issues.. is more an "elegance" issue IMHO. 
The main difference with the `current_block_index` is that we want it the same across the different threads, in contrast with `db`, that we want it different in each thread.
With a global variable is become very tricky for the API to have its own `db` instance I think. And pass around this `db` parameter make all those functions more flexible to use I think (more "stateless").

**Comment by adamkrellenstein** [comment]
'k. I'm convinced.
