### ISSUE TITLE
"Does anyone have problems with "counterpartyd server" just exiting after a while?"

### ISSUE THREAD

**Issue by goodtaster** [CounterpartyXCP/counterpartyd#651]
Don't have any more info on this. But figured I'd post it just in case.

**Comment by adamkrellenstein** [comment]
@goodtaster, what do the logs say? How long before it exits? What is its exit status when it does?

**Comment by goodtaster** [comment]
"Messages are just the same as what's shown on the console. I think it's happening when there is a large wait until the next block."

Supposedly it's often fine for days, or weeks. User says he will check the exit status the next time it happens.

**Comment by adamkrellenstein** [comment]
Have him check `dmesg` after the crash. Maybe he's running out of memory?

**Comment by mtbitcoin** [comment]
@goodtaster Does he have the "rpcthreads=1000 + rpctimeout=300" already set in bitcoind?

**Comment by adamkrellenstein** [comment]
Closing this, because it's unlikely to be a Counterparty issue. @goodtaster, feel free to follow up with me elsewhere, though.
