### ISSUE TITLE
counterparty-lib: alien commands on Windows

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterpartyd#656]
```
C:\Python34>pip -V
pip 1.4.1 from c:\python34\lib\site-packages\pip-1.4.1-py3.4.egg (python 3.4)

C:\Python34>pip install counterparty-lib
Downloading/unpacking counterparty-lib
  Downloading counterparty-lib-9.49.3.tar.gz (291kB): 291kB downloaded
  Running setup.py egg_info for package counterparty-lib
    'make' is not recognized as an internal or external command,
    operable program or batch file.
    'rm' is not recognized as an internal or external command,
    operable program or batch file.
    downloading serpent.
    extracting.
    install serpent.
    clean files.
```

**Comment by adamkrellenstein** [comment]
@rippler, I just updated the pip packages. Try again.

**Comment by rippler** [comment]
Okay, v9.49.4:

- Reminds to install `apsw` and `serpent` (perhaps it could check?)

- Maybe `sqlite3` should also be added to the list?
```
C:\Program Files\Microsoft Visual Studio 10.0\VC\BIN\cl.exe /c /nologo /Ox /MD /
W3 /GS- /DNDEBUG -DEXPERIMENTAL=1 -DNDEBUG=1 -DSQLITE_OMIT_LOAD_EXTENSION=1 -Isr
c -IC:\Python34\include -IC:\Python34\include /Tcsrc/apsw.c /Fobuild\temp.win32-
3.4\Release\src/apsw.obj
apsw.c
src/apsw.c(58) : fatal error C1083: Cannot open include file: 'sqlite3.h': No su
ch file or directory
error: command 'C:\\Program Files\\Microsoft Visual Studio 10.0\\VC\\BIN\\cl.exe
' failed with exit status 2
----------------------------------------
  Rolling back uninstall of apsw
Cleaning up...
```

Apsw needs pysqlite and pysqlite needs sphinx. But even after I install sphinx, pyslite fails to install regardless of whether sphinx 1.2.3 is installed or not (https://github.com/ghaering/pysqlite/issues/71). Unless I find a way around this I can't say whether this fix works. Let's leave this open for now.

**Comment by ouziel-slama** [comment]
`apsw` should be installed manually in Windows. 
To install `counterparty-cli` from the source in Windows :
- install all the prerequisites described here: http://counterparty.io/docs/build-system/build-from-source/
- install  `python-bitcoinlib` (temporary)
- `pip install counterparty-cli`

**Comment by adamkrellenstein** [comment]
@ouziel-slama, that first link is broken. Here's the new list: https://github.com/CounterpartyXCP/Documentation/blob/master/Installation/windows.md
