### ISSUE TITLE
In process of counterparty-lib install "requests" package is malformed

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterpartyd#664]
* Ubuntu 14.04, up to date
* Problem: when `counterparty-lib` is installed with `pip3`, it creates (or rather `pip3` does on its behalf) two `requests` package directories:
```
drwxr-sr-x  4 root staff    4096 Jan 25 04:44 requests/
drwxr-sr-x  2 root staff    4096 Jan 25 04:44 requests-2.4.2.dist-info/
```
After that, `pip3` is broken and can't work any more.

Workaround:
```
cd /usr/local/lib/python3.4/dist-packages
sudo mv requests requests.old
```
Reference:
https://bugs.launchpad.net/ubuntu/+source/python-pip/+bug/1306991/comments/36 (my comment)
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=744145 (additional background)

When `pip3` is not used (clone https://github.com/CounterpartyXCP/counterpartyd/archive/9.49.4.zip, install), then `requests` does not appear).

**Comment by adamkrellenstein** [comment]
Upstream bug
