### ISSUE TITLE
Make Install Smoother

### ISSUE THREAD

**Issue by atweiden** [CounterpartyXCP/counterpartyd#673]
Recently, PyPi dependency resolution has gotten out of hand. During linux builds, python has been manually downloading and resolving dependency trees when I build counterparty pkgs. I don't know where this strange behavior came from, today is the first time it's happened. I'm having to do an unholy amount of sed to make things work:

```sh
msg 'Fixing setup.py...'
sed -i "/^# In Windows.*/,/^- Serpent.*/d" setup.py
sed -i "s/python-bitcoinlib==.*/python-bitcoinlib'/" setup.py
sed -i "s/json-rpc==.*/json-rpc'/" setup.py
sed -i "s/python-dateutil==.*/python-dateutil'/" setup.py
```

From my perspective it warrants a different approach to linux packaging. I'm thinking it's necessary to package everything inside virtualenvs.

What are your thoughts on using [spotify/dh-virtualenv](https://github.com/spotify/dh-virtualenv) and creating native Debian packages for Counterparty with a [ppa](http://askubuntu.com/questions/71510/how-do-i-create-a-ppa)?

**Comment by robby-dermody** [comment]
+1 for utilizing virtualenv ... I haven't looked much into dh-virtualenv but it looks interesting. .deb packages would be a plus, but there has to be a path for developers working on the source, where they can quickly edit a file (under version control) and test the changes. (note: that's one of the issues with the current situation...if you check out the source, you really need to do a "python setup.py install" again before you test your changes.... not a super big deal, but it's one more step in the edit-build-test loop.

**Comment by adamkrellenstein** [comment]
I don't understand what the problem is here. Do you just want Debian packages from virtualenvs? That's for a Debian package maintainer to take up. What's the cause of the dependency hell? Is it that we're being too specific with the version requirements? (Versions which Debian doesn't like?) I'm OK with loosening up the restrictions there.

@robby-dermody, very often in testing I'll execute the source files in place, instead of installing them first.

**Comment by atweiden** [comment]
By using `pip` or `npm` to fetch and build programming language deps, you don't have to worry at all about dependency hell, and you can still use the native linux package manager for actual installation. A good example is [nodejs-bitcoin](https://github.com/atweiden/pkgbuilds/blob/master/nodejs-sx/PKGBUILD). It specifies [sx](https://github.com/spesmilo/sx) as a dependency while simultaneously allowing `npm` to resolve NPM deps, and the resulting package is tracked for installation/uninstallation by `pacman`.

The Counterparty parallel would be specifying [ethereum-serpent](https://github.com/ethereum/serpent) as an `apt` dependency instead of building and sudo installing it from [setup.py](https://github.com/CounterpartyXCP/counterpartyd/blob/develop/setup.py#L89).

> Is it that we're being too specific with the version requirements?

No. Versioning is fine, but the more deps you have, the hairier it gets to write out all of the correct deps by hand for `apt-get`. You'd rather that part of installation be automatically managed by `pip`.

**Comment by adamkrellenstein** [comment]
This is largley outside the scope of this project. We can't get into distribution-specific packaging, and we shouln't be packaging our software as a virtual environment (that's for a distribution's package maintainer to do.)

All of counterparty-lib's dependencies (with only a couple of fragile/new/temporary exceptions, namely 'apsw' and `ethereum-serpent`) can be satisfied by local package management: we install PyPi packages wherever possible. (And @ouziel-slama is looking into the situation with `serpent`.)

What we *can* do here is loosen up the restrictions on the versions of dependencies, and that should help a lot with avoiding dependency hell. @ouziel-slama, would you take a crack at this (if possible, before we release v9.49.4)?

**Comment by ouziel-slama** [comment]
done

**Comment by rippler** [comment]
@adamkrellenstein with the newest code (9.49.4rc), I've seen most problems with `apsw`, especially on older distros (e.g. Debian 7) and with `requests` (issue recorded here, it's pip3-related, and a workaround exists). This sometimes happen even on Ubuntu 14.04.

If the intent is to support (or give people a chance to easier accomplish that on their own) `counterparty-lib` a wider number of OS and versions, I think we could relax version details in dependencies (especially if it's possible to run a test suite to confirm the s/w works fine following the installation).

**Comment by adamkrellenstein** [comment]
There's nothing we can do `requests`, right? We're thinking about what to do with `apsw`. :/

**Comment by rippler** [comment]
Maybe we could leave `apsw` completely to the user, just like it's done on Windows (that's the only OS on which I didn't have any problems with `apsw` as long as I used the binary package installer).

**Comment by ouziel-slama** [comment]
see this commit https://github.com/ouziel-slama/counterpartyd/commit/4aa142d728f1975a0b4b8299dd1b2e2e9907c4c1
Ideally, all python packages should be installed by `pip`. And no-python requirements should be installed manually or with a specific option:
`python setup.py install --with-sqlite --with-serpent`

But for now it's not works like this:
https://travis-ci.org/ouziel-slama/counterpartyd/builds/48788813
I'am making more tests but I'am not sure if it's possible to install `apsw` with a specific method. (Don't understand why is impossible in the `setup.py` to pass options for the installation of each package..)

**Comment by rippler** [comment]
@ouziel-slama, example of `apsw` being installed by `pip3` in CentOS 6.5 (or maybe 6.6, I don't remember).
```
    gcc -pthread -Wno-unused-result -Werror=declaration-after-statement -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DEXPERIMENTAL=1 -DNDEBUG=1 -DAPSW_FORK_CHECKER=1 -DSQLITE_OMIT_LOAD_EXTENSION=1 -Isrc -I/usr/local/include/python3.4m -c src/apsw.c -o build/temp.linux-x86_64-3.4/src/apsw.o
    src/apsw.c:62:2: error: #error Your SQLite version is too old. It must be at least 3.8.7
```

**Comment by ouziel-slama** [comment]
Yeah, it's the classical error. See the note here https://pypi.python.org/pypi/apsw/3.8.5-r1:

> Unfortunately a version of apsw will generally only work with a specific version of SQLite. There are no provisions to detect SQLite version and expose an appropriate API. Be mindful of the version of SQLite you have installed. Also be mindful of updates to apsw. If you need a specific version of apsw or need to build against a specific version of SQLite then please follow these instuctions -> http://rogerbinns.github.io/apsw/build.html#recommended

That why is so useful to install `apsw` with the command `fetch` and `build`: https://github.com/CounterpartyXCP/counterpartyd/blob/develop/setup.py#L48

**Comment by adamkrellenstein** [comment]
@ouziel-slama, what if we just used a (much?) older version of `apsw`? Can the local SQLite3 be too *new* ever?

**Comment by ouziel-slama** [comment]
hum.. I need to do more test to be able to answer, but I'am not sure that is a good idea to use an `=={an_old_version}` and if we use are using an `>={old_version}`, it's also the most recent that is installed.

**Comment by atweiden** [comment]
I figured out how to install this using virtualenvs, and relaxed deps was helpful, but the process is suboptimal compared to what was working a few weeks ago. In short, I narrowed down the cause of all of these new problems to the egg install method (`git diff -r 8618d6f2ab77e6094c98dd69835de29a4744a559 -r 5111b9d097e8415474af187df97f57beb50b64f8 setup.py`):

```python
class install(_install):
    def run(self):
        _install.do_egg_install(self)
        post_install(self)

class bdist_egg(_bdist_egg):
    def run(self):
        _bdist_egg.run(self)
        post_install(self)
```

This is how the counterparty packages are having to look now (virtualenv installation is in practice not as clean as `npm`):

```bash
prepare() {
  cd ${pkgname%-git}

  msg 'Fixing setup.py...'
  sed -i "/cmd.run_command('install_serpent')/d" setup.py
}

build() {
  cd ${pkgname%-git}

  msg 'Building...'
  vex --path "$srcdir/${pkgname%-git}/vex" --always-copy -mr <<EOF
install -dm 755 "$srcdir/${pkgname%-git}/vex/lib/python3.4/site-packages"
PYTHONPATH="$srcdir/${pkgname%-git}/vex/lib/python3.4/site-packages" \
python setup.py install --prefix="$srcdir/${pkgname%-git}/vex" --optimize=1
cp -dpr --no-preserve=owner "$srcdir/${pkgname%-git}/vex" "$srcdir/${pkgname%-git}/vex.bak"
EOF
}

package() {
  cd ${pkgname%-git}

  msg 'Installing...'
  install -dm 755 "$pkgdir/usr/share/counterparty-lib"
  find vex.bak -mindepth 1 -maxdepth 1 -exec \
    cp -dpr --no-preserve=owner '{}' "$pkgdir/usr/share/counterparty-lib" \;

  msg 'Cleaning up Python dist info...'
  find "$pkgdir" -type f -print0 | xargs -0 sed -i "s@$srcdir/${pkgname%-git}/vex@/usr/share/counterparty-lib@g"
  sed -i 's@^VIRTUAL_ENV=.*@VIRTUAL_ENV="/usr/share/counterparty-lib"@' "$pkgdir/usr/share/counterparty-lib/bin/activate"
  sed -i 's@^setenv VIRTUAL_ENV.*@setenv VIRTUAL_ENV "/usr/share/counterparty-lib"@' "$pkgdir/usr/share/counterparty-lib/bin/activate.csh"
  sed -i 's@^set -gx VIRTUAL_ENV.*@set -gx VIRTUAL_ENV "/usr/share/counterparty-lib"@' "$pkgdir/usr/share/counterparty-lib/bin/activate.fish"
}
```

It involves building everything in a virtualenv and then installing the virtualenv to /usr/share/counterparty-lib. This is working, but now other packages cannot depend on counterparty-lib being installed globally.  I would understand if this isn't a concern, or if most developers are building virtualenvs and not installing global python packages.

You can still run setup.py install for a global installation, but it becomes a problem when installing counterparty-lib individually and then installing counterparty-cli individually, which is how package managers do it. Both counterparty-lib and counterparty-cli end up wanting to write to the same file `/usr/lib/python-3.4/site-packages/site.py`, which creates a conflict. There are several more file conflicts.

The other problem created by this method is pip redundantly building dependency trees even if they are installed currently to the system.  That is the root cause for my opening #673. The weirdness definitely comes from the new egg install method which I have not seen many other pypi packages use (and I have packaged [quite a few of them](https://github.com/atweiden/pkgbuilds)).

Assuming the egg install method isn't reverted from setup.py, if I am to maintain arch packages for counterparty, the ethereum-serpent build must be removed from setup.py. Invoking sudo from within arch PKGBUILDs is forbidden. This unfortunately cannot be worked around because in the virtualenv method, with `pip` pulling down deps, there is no opportunity to fix setup.py with `sed`.

**Comment by adamkrellenstein** [comment]
We'll remove the `ethereum-serpent` install from the default behavior, as it's only required for the test suite anyway.

What's the alternative to that egg install method? How do we avoid the file conflicts (e.g. with `site.py`)?

**Comment by ouziel-slama** [comment]
@atweiden, I'am not sure to understand when the file conflict occurs (with `site.py`).. 
How I can reproduce it on a fresh VM ?

**Comment by atweiden** [comment]
@adamkrellenstein, I've seen pypi modules use [wheel](http://pythonwheels.com/), e.g.:

- https://github.com/numpy/numpy
- https://github.com/sbuss/bitmerchant

Reverting it is another option.

@ouziel-slama, can you run [ArchBang](http://sourceforge.net/projects/archbang/files/?source=navbar) on virtualbox? Then copy/paste this script:

```bash
#!/bin/bash

# fetching counterparty-lib AUR dependencies
sudo pacman -Syyu # upgrade system for good measure
sudo pacman -S base-devel # install utilities needed for building AUR packages
for aurpkg in python-appdirs \
              python-colorlog \
              python-flask-httpauth \
              python-json-rpc \
              python-plyvel \
              python-pycoin \
              python-pysha3 \
              python-python-bitcoinlib \
              python-tendo; do
  mkdir -p pkgbuilds && pushd pkgbuilds
  rm -rf ${aurpkg} ${aurpkg}.tar.gz*
  curl -O https://aur.archlinux.org/packages/${aurpkg:0:2}/${aurpkg}/${aurpkg}.tar.gz
  mkdir -p ${aurpkg}
  tar -xvzf ${aurpkg}.tar.gz --strip 1 -C ${aurpkg}
  cd ${aurpkg}
  makepkg -Acsi --noconfirm
  popd
done

# building counterparty-lib and counterparty-cli (worked ok pre-egg-install method)
for aurpkg in python-counterparty-lib-git \
              counterparty-cli-git; do
  mkdir -p pkgbuilds && pushd pkgbuilds
  rm -rf ${aurpkg} ${aurpkg}.tar.gz*
  curl -O https://aur.archlinux.org/packages/${aurpkg:0:2}/${aurpkg}/${aurpkg}.tar.gz
  mkdir -p ${aurpkg}
  tar -xvzf ${aurpkg}.tar.gz --strip 1 -C ${aurpkg}
  cd ${aurpkg}
  makepkg -Acsi --noconfirm
  popd
done
```

**Comment by adamkrellenstein** [comment]
@atweiden, the reason we haven't been using the wheel package format (not that we could use it exclusively) is that it doesn't play well with our manual installation of APSW, which doesn't have an official PyPi package.

Reverting what?

**Comment by atweiden** [comment]
The previous [setup.py](https://github.com/CounterpartyXCP/counterpartyd/blob/8618d6f2ab77e6094c98dd69835de29a4744a559/setup.py) without the egg install methods worked ok, but I do not know the reasons for the egg install methods being introduced.

**Comment by adamkrellenstein** [comment]
@ouziel-slama, can we go back to the old way, do you know?

**Comment by ouziel-slama** [comment]
hum.. it was an ugly and non standard way to do what we want.. The `setup.py` is supposed to be used with PIP and only with PIP. The method we are using is the correct way to add post-install tasks in the `setup.py`. If you want to use the `setup.py` in a non standard way. You have to:
- extract manually the list of dependencies
- take care to install APSW (and eventually Serpent)

**Comment by adamkrellenstein** [comment]
@atweiden, is that what you're suggesting? If not, can you make a PR?

**Comment by adamkrellenstein** [comment]
@atweiden, @ouziel-slama, sorry I'm still catching up here... what about this?

```
        if caller_module != 'distutils.dist' or caller_name!='run_commands':
            # We weren't called from the command line or setup(), so we
            # should run in backward-compatibility mode to support bdist_*
            # commands.
            old_install_mod._install.run(self)
        else:
            self.do_egg_install() # NOTE: Not `_install.do_egg_install(self)`?
```

**Comment by ouziel-slama** [comment]
@adamkrellenstein: good catch! it's because this `if` in the `setuptools`code, that [here](https://github.com/CounterpartyXCP/counterpartyd/blob/develop/setup.py#L143) I'am using `_install.do_egg_install(self)` instead `_install.run(self)` (don't work with the latter). 
Are you suggesting to reproduce this `if` in our `setup.py`.

(Yes you right, `self.do_egg_install()` is cleaner than `_install.do_egg_install(self)`!)

**Comment by adamkrellenstein** [comment]
@ouziel-slama, OK, I'm making progress on understanding the situation. :/ Why doesn't `_install.run(self)` work, though? Do we need to call `post_install()` in two different places in our `setup.py`?

**Comment by ouziel-slama** [comment]
@adamkrellenstein: I admit I did not look further, as soon as it worked ;-) for what I understand `bdist_egg` is the new `install` command. So you right it's enough to extend only `bdist_egg` class.. but we need also to extend  `install` to be able to add options for the `install` command (eg. --with-serpent).
