### ISSUE TITLE
counterparty-server shows duplicate data

### ISSUE THREAD

**Issue by cryptodock** [CounterpartyXCP/counterpartyd#675]
All output shown in counterparty-server is duplicated:

example:[INFO] Running v1.0.0 of counterparty-server.
[INFO] Loading configuration file: `/home/counterparty/.config/counterparty-server/counterparty-server.conf`
[INFO] Running v9.49.3 of counterparty-lib.
[INFO] Running v9.49.3 of counterparty-lib.
[INFO] Acquiring lock.
[INFO] Acquiring lock.
[INFO] Connecting to database.
[INFO] Connecting to database.
[INFO] Connecting to backend.
[INFO] Connecting to backend.
[INFO] Starting API Server.
[INFO] Starting API Server.
[INFO] Resuming parsing.
[INFO] Resuming parsing.
[INFO] Block: 281146 (0.35s)
[INFO] Block: 281146 (0.35s)
[INFO] Issuance: 1LMPuuw781iW3NJz2GYAjqg1m14s5zQ4Yy created 9223372036854775807 of indivisible asset CRUDEOIL (2c43ac1fec79f7dec7218e6606e24fd9ad6116d3083cb6f4dc0297c238072a3d) [valid]
[INFO] Issuance: 1LMPuuw781iW3NJz2GYAjqg1m14s5zQ4Yy created 9223372036854775807 of indivisible asset CRUDEOIL (2c43ac1fec79f7dec7218e6606e24fd9ad6116d3083cb6f4dc0297c238072a3d) [valid]
[INFO] Block: 281147 (0.67s)
[INFO] Block: 281147 (0.67s)
[INFO] Block: 281148 (1.16s)
[INFO] Block: 281148 (1.16s)

**Comment by adamkrellenstein** [comment]
Fixed already: https://github.com/CounterpartyXCP/counterparty-cli/commit/35b57630cb6641e55e906b274d212a44949c870f
