### ISSUE TITLE
Keep Server Running even with Patchy Internet Access?

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterpartyd#677]

**Comment by ouziel-slama** [comment]
Yes, I think even with no internet connection at all: one could decide to run the RPC server, but no the synchronisation..

**Comment by adamkrellenstein** [comment]
You can do that now, but you have to use `--force` (because your local DB will be out-of-date).

**Comment by ouziel-slama** [comment]
ah yes right!

**Comment by adamkrellenstein** [comment]
What this would be useful for is stopping the server from shutting down, even if the API temporarily stopped working.
