### ISSUE TITLE
Terminology: change "location" to "path with filename"

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterpartyd#679]
```
 --data-dir DATA_DIR   the directory in which to keep the database, config
                       file and log file, by default
 --config-file CONFIG_FILE
                       the location of the configuration file
```
I propose that the in places where `location` is used to mean `path and filename`, it be changed.
It is not necessary to change option name(s), but just the explanation of what it means.

**Comment by adamkrellenstein** [comment]
Solved: https://github.com/CounterpartyXCP/counterparty-cli/commit/44e1d8d06590634c46164a4f45731ea8c5ad92cf
