### ISSUE TITLE
Get Rid of Signing and Broadcast Functionality

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterpartyd#683]
Because `counterparty-lib` no longer connects to a wallet, all of the signing only works when you're passing the private key around (and even then it's only implemented with a horrible hack). Better would be to require people to sign with the wallet themselves (e.g. with `signrawtransaction`) and broadcast on their own, too.

Really all of this should be in the CLI, anyway. I propose also getting rid of `transaction.sign_tx()`, `transaction.broadcast_tx()`, `api.sign_transaction()` and `api.do_*()`. (The functions from `transaction.py` can be moved to the CLI.)

<s>If we don't do this, we need to restore manual signing functionality here: https://github.com/CounterpartyXCP/counterparty-cli/blob/develop/counterpartycli/client.py#L298</s>

**Comment by ouziel-slama** [comment]
Yeah I agree we should remove all signing features in `counterparty-lib`.
In `counterparty-cli` what do you think to ask the private key, if the address is not in the wallet, and doing a `importprivkey` ?

**Comment by adamkrellenstein** [comment]
We definitely can't do `importprivkey`...

We can move the `pybtctools` hack over to the CLI for now.

**Comment by robby-dermody** [comment]
ok, with a few caveats:

* signing functionality is implemented in the CLI, and easy to use
* the API docs are updated to include an example of signing, maybe? there are so many language lib combos though, but possibly a jquery and bitcore example would be best, since a lot of the use is webapps
* @ouziel-slama feels comfortable about making the necessary changes to counterwallet, and doesn't see this as an issue there

**Comment by adamkrellenstein** [comment]
> the API docs are updated to include an example of signing, probably? there are so many language lib combos though, but possibly a jquery and bitcore example would be best, since a lot of the use is webapps (@ouziel-slama should be able to quickly provide the code for this, I would think)

@ouziel-slama, I have a Bitcoin Core example here: https://github.com/CounterpartyXCP/Documentation/blob/master/Developers/API.md#wallet-integration

**Comment by adamkrellenstein** [comment]
>  signing functionality is implemented in the CLI, and easy to use

I actually don't think we should move the `pybtctool` hack over to the CLI. It's very unreliable (@evanwagner1 says it doesn't work at all!), and if someone wants to sign a transaction on the CLI, there's no reason he should use `counterparty-cli` to do it.

Signing with Bitcoin Core, on the other hand, is implemented and working well.

**Comment by adamkrellenstein** [comment]
@ouziel-slama, if you're OK with how this'll work with CW and you'll add some more examples to the Wallet Integration section of the API docs, we can close this issue.

**Comment by ouziel-slama** [comment]
It will work fine with CW, because we are signing transactions in the browser with Javascript.

I did a PR for the doc: https://github.com/CounterpartyXCP/Documentation/pull/34
