### ISSUE TITLE
9.49.4rc7 password field can't handle @

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterpartyd#685]
Spent an ungodly amount of time to figure this out...

`counterparty-server` reports that it can't connect to backend.

**Comment by adamkrellenstein** [comment]
Which password field?

**Comment by adamkrellenstein** [comment]
`backend-password`?

**Comment by adamkrellenstein** [comment]
We could use `urllib.parse`?

**Comment by ouziel-slama** [comment]
@adamkrellenstein : yes!
fixed here https://github.com/CounterpartyXCP/counterpartyd/commit/1c3d9c1b5613698356d79f13cffb2f2f1eac22fc

**Comment by adamkrellenstein** [comment]
Perfect! :)
