### ISSUE TITLE
Disable Authentication for JSON-RPC API by Default

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterpartyd#687]

**Comment by Millz0r** [comment]
Since I am working on REST/RPC I also added this to my backlog, I got it implemented via a conditional decorator - however what should I base the condition on? Should we add another configuration option, eg. api_auth = 0?

**Comment by adamkrellenstein** [comment]
Shouldn't we just disable authentication if there's no password set?

**Comment by Millz0r** [comment]
That is reasonable, would just need to change that:
https://github.com/CounterpartyXCP/counterpartyd/blob/master/counterpartylib/server.py#L244
