### ISSUE TITLE
Remove major version for the database file name

### ISSUE THREAD

**Issue by ouziel-slama** [CounterpartyXCP/counterpartyd#689]
We could maybe just launch a `rollback START_BLOCK` when there is a major version change, like we are launching a `reparse` when there is a minor version change.

**Comment by adamkrellenstein** [comment]
ACK!

**Comment by adamkrellenstein** [comment]
We'd have to store the major version number in the db somehow, however.

**Comment by ouziel-slama** [comment]
yep! so maybe we should include this issue in the `v9.49.4`? then the `setup.py` will move an rename the database directly with the final name.

**Comment by adamkrellenstein** [comment]
Yeah, I guess. Can you implement and test it?

**Comment by ouziel-slama** [comment]
sure!

**Comment by adamkrellenstein** [comment]
Haha! That's an awful hack, but sure. :) It's still much better than using the filename.

**Comment by ouziel-slama** [comment]
:-) ok go for it!

**Comment by adamkrellenstein** [comment]
@ouziel-slama, je crois que tu voulais dire "OK, **let's** go for it". ;)

**Comment by ouziel-slama** [comment]
:-)) yeah thank you! fixed :-)
