### ISSUE TITLE
counterparty-server not starting up after update

### ISSUE THREAD

**Issue by cryptodock** [CounterpartyXCP/counterpartyd#699]
after upgrade counterparty-server not starting again:

counterparty-server
Traceback (most recent call last):
  File "/usr/local/bin/counterparty-server", line 11, in <module>
    sys.exit(server_main())
  File "/usr/local/lib/python3.4/dist-packages/counterparty_cli-1.0.0-py3.4.egg/counterpartycli/__init__.py", line 15, in server_main
    from counterpartycli import server
  File "/usr/local/lib/python3.4/dist-packages/counterparty_cli-1.0.0-py3.4.egg/counterpartycli/server.py", line 33, in <module>
    [('--rpc-port',), {'type': int, 'help': 'port on which to provide the {} JSON-RPC API'.format(config.APP_NAME)}],
AttributeError: 'module' object has no attribute 'APP_NAME'

tried to uninstall and reinstall however same.

my counterparty-server.conf:

[Default]
backend-name = addrindex
backend-connect = localhost
backend-port = 45455
backend-user = replaced
backend-password = replaced
rpc-host = 127.0.0.1
rpc-port = 9976
rpc-user = replaced
rpc-password = replaced

I am sorry if I am missing something but that same config worked minutes ago

**Comment by cryptodock** [comment]
Ok, the situation goes like that, after uninstalling and installing several times the error is now:

counterparty-server
Traceback (most recent call last):
  File "/usr/local/bin/counterparty-server", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: counterparty-cli==1.0.0

There is also a warning after the install "Could not find .egg-info directory in install record for counterparty-lib" 


 sudo pip3 install --pre counterparty-lib
Downloading/unpacking counterparty-lib
  Downloading counterparty-lib-9.49.4.0.tar.gz (293kB): 293kB downloaded
  Running setup.py (path:/tmp/pip_build_root/counterparty-lib/setup.py) egg_info for package counterparty-lib

Requirement already satisfied (use --upgrade to upgrade): appdirs>=1.4.0 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil>=2.2 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): flask>=0.10.1 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): Flask-HTTPAuth>=2.3.0 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): json-rpc>=1.7 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): pytest>=2.6.4 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): pytest-cov>=1.8.0 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): pycoin>=0.52 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): requests>=2.3.0 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): tornado>=4.0 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): pycrypto>=2.6 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): tendo>=0.2.6 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): pysha3>=0.3 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): colorlog>=2.4.0 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): python-bitcoinlib>=0.2.1 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in /usr/local/lib/python3.4/dist-packages (from python-dateutil>=2.2->counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): Werkzeug>=0.7 in /usr/local/lib/python3.4/dist-packages (from flask>=0.10.1->counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in /usr/local/lib/python3.4/dist-packages (from flask>=0.10.1->counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in /usr/local/lib/python3.4/dist-packages (from flask>=0.10.1->counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): py>=1.4.25 in /usr/local/lib/python3.4/dist-packages (from pytest>=2.6.4->counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): coverage>=3.7.1,<4.0a1 in /usr/local/lib/python3.4/dist-packages (from pytest-cov>=1.8.0->counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): cov-core>=1.14.0 in /usr/local/lib/python3.4/dist-packages (from pytest-cov>=1.8.0->counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): certifi in /usr/local/lib/python3.4/dist-packages (from tornado>=4.0->counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): markupsafe in /usr/local/lib/python3.4/dist-packages (from Jinja2>=2.4->flask>=0.10.1->counterparty-lib)
Installing collected packages: counterparty-lib
  Running setup.py install for counterparty-lib
    Checking .pth file support in /usr/local/lib/python3.4/dist-packages/
    /usr/bin/python3 -E -c pass
    TEST PASSED: /usr/local/lib/python3.4/dist-packages/ appears to support .pth files

    installing library code to build/bdist.linux-x86_64/egg
    removing 'build/bdist.linux-x86_64/egg' (and everything under it)
    Processing counterparty_lib-9.49.4-py3.4.egg
    Extracting counterparty_lib-9.49.4-py3.4.egg to /usr/local/lib/python3.4/dist-packages
    Adding counterparty-lib 9.49.4 to easy-install.pth file

    Installed /usr/local/lib/python3.4/dist-packages/counterparty_lib-9.49.4-py3.4.egg
    Processing dependencies for counterparty-lib==9.49.4
    Searching for python-bitcoinlib==0.2.1
    Best match: python-bitcoinlib 0.2.1
    python-bitcoinlib 0.2.1 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Searching for colorlog==2.6.0
    Best match: colorlog 2.6.0
    colorlog 2.6.0 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Searching for pysha3==0.3
    Best match: pysha3 0.3
    pysha3 0.3 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Searching for tendo==0.2.7
    Best match: tendo 0.2.7
    tendo 0.2.7 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Searching for pycrypto==2.6.1
    Best match: pycrypto 2.6.1
    pycrypto 2.6.1 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Searching for tornado==4.1b2
    Best match: tornado 4.1b2
    tornado 4.1b2 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Searching for requests==2.5.1
    Best match: requests 2.5.1
    requests 2.5.1 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Searching for pycoin==0.52
    Best match: pycoin 0.52
    pycoin 0.52 is already the active version in easy-install.pth
    Installing genwallet script to /usr/local/bin
    Installing fetch_unspent script to /usr/local/bin
    Installing cache_tx script to /usr/local/bin
    Installing tx script to /usr/local/bin
    Installing block script to /usr/local/bin
    Installing ku script to /usr/local/bin
    Installing spend script to /usr/local/bin
    Installing bu script to /usr/local/bin

    Using /usr/local/lib/python3.4/dist-packages
    Searching for pytest-cov==1.8.1
    Best match: pytest-cov 1.8.1
    pytest-cov 1.8.1 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Searching for pytest==2.6.4
    Best match: pytest 2.6.4
    pytest 2.6.4 is already the active version in easy-install.pth
    Installing py.test-3.4 script to /usr/local/bin
    Installing py.test script to /usr/local/bin

    Using /usr/local/lib/python3.4/dist-packages
    Searching for json-rpc==1.8.1
    Best match: json-rpc 1.8.1
    json-rpc 1.8.1 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Searching for Flask-HTTPAuth==2.3.0
    Best match: Flask-HTTPAuth 2.3.0
    Flask-HTTPAuth 2.3.0 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Searching for Flask==0.10.1
    Best match: Flask 0.10.1
    Flask 0.10.1 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Searching for python-dateutil==2.4.0
    Best match: python-dateutil 2.4.0
    python-dateutil 2.4.0 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Searching for appdirs==1.4.0
    Best match: appdirs 1.4.0
    appdirs 1.4.0 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Searching for certifi==14.05.14
    Best match: certifi 14.05.14
    certifi 14.05.14 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Searching for cov-core==1.15.0
    Best match: cov-core 1.15.0
    cov-core 1.15.0 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Searching for coverage==3.7.1
    Best match: coverage 3.7.1
    coverage 3.7.1 is already the active version in easy-install.pth
    Installing coverage script to /usr/local/bin
    Installing coverage-3.4 script to /usr/local/bin
    Installing coverage3 script to /usr/local/bin

    Using /usr/local/lib/python3.4/dist-packages
    Searching for py==1.4.26
    Best match: py 1.4.26
    py 1.4.26 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Searching for itsdangerous==0.24
    Best match: itsdangerous 0.24
    itsdangerous 0.24 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Searching for Jinja2==2.7.3
    Best match: Jinja2 2.7.3
    Jinja2 2.7.3 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Searching for Werkzeug==0.10.1
    Best match: Werkzeug 0.10.1
    Werkzeug 0.10.1 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Searching for six==1.9.0
    Best match: six 1.9.0
    six 1.9.0 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Searching for MarkupSafe==0.23
    Best match: MarkupSafe 0.23
    MarkupSafe 0.23 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Finished processing dependencies for counterparty-lib==9.49.4
  Could not find .egg-info directory in install record for counterparty-lib
Successfully installed counterparty-lib
Cleaning up...

**Comment by cryptodock** [comment]
tried to reinstall:
sudo pip3 uninstall counterparty-lib
Uninstalling counterparty-lib:
  /usr/local/lib/python3.4/dist-packages/counterparty_lib-9.49.4-py3.4.egg
Proceed (y/n)? y
  Successfully uninstalled counterparty-lib


install goes same as message above:

sudo pip3 install counterparty-lib
Downloading/unpacking counterparty-lib
  Downloading counterparty-lib-9.49.4.0.tar.gz (293kB): 293kB downloaded
  Running setup.py (path:/tmp/pip_build_root/counterparty-lib/setup.py) egg_info for package counterparty-lib

Requirement already satisfied (use --upgrade to upgrade): appdirs>=1.4.0 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil>=2.2 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): flask>=0.10.1 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): Flask-HTTPAuth>=2.3.0 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): json-rpc>=1.7 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): pytest>=2.6.4 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): pytest-cov>=1.8.0 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): pycoin>=0.52 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): requests>=2.3.0 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): tornado>=4.0 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): pycrypto>=2.6 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): tendo>=0.2.6 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): pysha3>=0.3 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): colorlog>=2.4.0 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): python-bitcoinlib>=0.2.1 in /usr/local/lib/python3.4/dist-packages (from counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in /usr/local/lib/python3.4/dist-packages (from python-dateutil>=2.2->counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): Werkzeug>=0.7 in /usr/local/lib/python3.4/dist-packages (from flask>=0.10.1->counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in /usr/local/lib/python3.4/dist-packages (from flask>=0.10.1->counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in /usr/local/lib/python3.4/dist-packages (from flask>=0.10.1->counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): py>=1.4.25 in /usr/local/lib/python3.4/dist-packages (from pytest>=2.6.4->counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): coverage>=3.7.1,<4.0a1 in /usr/local/lib/python3.4/dist-packages (from pytest-cov>=1.8.0->counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): cov-core>=1.14.0 in /usr/local/lib/python3.4/dist-packages (from pytest-cov>=1.8.0->counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): certifi in /usr/local/lib/python3.4/dist-packages (from tornado>=4.0->counterparty-lib)
Requirement already satisfied (use --upgrade to upgrade): markupsafe in /usr/local/lib/python3.4/dist-packages (from Jinja2>=2.4->flask>=0.10.1->counterparty-lib)
Installing collected packages: counterparty-lib
  Running setup.py install for counterparty-lib
    Checking .pth file support in /usr/local/lib/python3.4/dist-packages/
    /usr/bin/python3 -E -c pass
    TEST PASSED: /usr/local/lib/python3.4/dist-packages/ appears to support .pth files

    installing library code to build/bdist.linux-x86_64/egg
    removing 'build/bdist.linux-x86_64/egg' (and everything under it)
    Processing counterparty_lib-9.49.4-py3.4.egg
    Extracting counterparty_lib-9.49.4-py3.4.egg to /usr/local/lib/python3.4/dist-packages
    Adding counterparty-lib 9.49.4 to easy-install.pth file

    Installed /usr/local/lib/python3.4/dist-packages/counterparty_lib-9.49.4-py3.4.egg
    Processing dependencies for counterparty-lib==9.49.4
    Searching for python-bitcoinlib==0.2.1
    Best match: python-bitcoinlib 0.2.1
    python-bitcoinlib 0.2.1 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Searching for colorlog==2.6.0
    Best match: colorlog 2.6.0
    colorlog 2.6.0 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Searching for pysha3==0.3
    Best match: pysha3 0.3
    pysha3 0.3 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Searching for tendo==0.2.7
    Best match: tendo 0.2.7
    tendo 0.2.7 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Searching for pycrypto==2.6.1
    Best match: pycrypto 2.6.1
    pycrypto 2.6.1 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Searching for tornado==4.1b2
    Best match: tornado 4.1b2
    tornado 4.1b2 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Searching for requests==2.5.1
    Best match: requests 2.5.1
    requests 2.5.1 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Searching for pycoin==0.52
    Best match: pycoin 0.52
    pycoin 0.52 is already the active version in easy-install.pth
    Installing spend script to /usr/local/bin
    Installing fetch_unspent script to /usr/local/bin
    Installing cache_tx script to /usr/local/bin
    Installing genwallet script to /usr/local/bin
    Installing ku script to /usr/local/bin
    Installing tx script to /usr/local/bin
    Installing bu script to /usr/local/bin
    Installing block script to /usr/local/bin

    Using /usr/local/lib/python3.4/dist-packages
    Searching for pytest-cov==1.8.1
    Best match: pytest-cov 1.8.1
    pytest-cov 1.8.1 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Searching for pytest==2.6.4
    Best match: pytest 2.6.4
    pytest 2.6.4 is already the active version in easy-install.pth
    Installing py.test-3.4 script to /usr/local/bin
    Installing py.test script to /usr/local/bin

    Using /usr/local/lib/python3.4/dist-packages
    Searching for json-rpc==1.8.1
    Best match: json-rpc 1.8.1
    json-rpc 1.8.1 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Searching for Flask-HTTPAuth==2.3.0
    Best match: Flask-HTTPAuth 2.3.0
    Flask-HTTPAuth 2.3.0 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Searching for Flask==0.10.1
    Best match: Flask 0.10.1
    Flask 0.10.1 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Searching for python-dateutil==2.4.0
    Best match: python-dateutil 2.4.0
    python-dateutil 2.4.0 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Searching for appdirs==1.4.0
    Best match: appdirs 1.4.0
    appdirs 1.4.0 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Searching for certifi==14.05.14
    Best match: certifi 14.05.14
    certifi 14.05.14 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Searching for cov-core==1.15.0
    Best match: cov-core 1.15.0
    cov-core 1.15.0 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Searching for coverage==3.7.1
    Best match: coverage 3.7.1
    coverage 3.7.1 is already the active version in easy-install.pth
    Installing coverage3 script to /usr/local/bin
    Installing coverage-3.4 script to /usr/local/bin
    Installing coverage script to /usr/local/bin

    Using /usr/local/lib/python3.4/dist-packages
    Searching for py==1.4.26
    Best match: py 1.4.26
    py 1.4.26 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Searching for itsdangerous==0.24
    Best match: itsdangerous 0.24
    itsdangerous 0.24 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Searching for Jinja2==2.7.3
    Best match: Jinja2 2.7.3
    Jinja2 2.7.3 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Searching for Werkzeug==0.10.1
    Best match: Werkzeug 0.10.1
    Werkzeug 0.10.1 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Searching for six==1.9.0
    Best match: six 1.9.0
    six 1.9.0 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Searching for MarkupSafe==0.23
    Best match: MarkupSafe 0.23
    MarkupSafe 0.23 is already the active version in easy-install.pth

    Using /usr/local/lib/python3.4/dist-packages
    Finished processing dependencies for counterparty-lib==9.49.4
  Could not find .egg-info directory in install record for counterparty-lib
Successfully installed counterparty-lib
Cleaning up...

**Comment by cryptodock** [comment]
nvm

**Comment by ouziel-slama** [comment]
great! 
for record seems the message "Could not find .egg-info directory in install record..." is a `setuptools` bug: http://stackoverflow.com/questions/26091641/what-does-a-could-not-find-egg-info-directory-in-install-record-from-pip-mean
