### ISSUE TITLE
setup.py should describe abstract (non-version numbered) dependencies only

### ISSUE THREAD

**Issue by miohtama** [CounterpartyXCP/counterpartyd#703]
It is a best practice to have only abstract, non-version numbered, dependencies in `setup.py`.

For exact tested known good set of versions (KGS) one can distribute `requirements.txt` which usage is described in the installation instructions.

* The developer can install this file directly using `pip install -r requirements`

* For the application, which is using `counterparty-lib`, the application maintainer can merge `requirements.txt` to the application specific `requirements.txt` or similar package version list (There are other Python package management tools like Buildout).

Please note that not having exact version pinnings will break `counterparty-lib` installation if any of dependency packages gets a new non-API-compatible release.

For more information 

* https://caremad.io/2013/07/setup-vs-requirement/

**Comment by ouziel-slama** [comment]
ACK. 
Great article thanks!
If @adamkrellenstein and @robby-dermody are OK, I will remove version number in `counterparty-lib`, and use a requirements.txt for `counterparty-cli`.

**Comment by adamkrellenstein** [comment]
ACK

**Comment by ouziel-slama** [comment]
done [here](https://github.com/CounterpartyXCP/counterpartyd/commit/1147d7d21960ca7eaa1dd8ba1c73a298ea3193c2) and [here](https://github.com/CounterpartyXCP/counterparty-cli/commit/0ab66903a178add19a64c0d71a439684849d495e).

**Comment by robby-dermody** [comment]
Sure. im not sure if it'll fully work with counterblock as well, as there are some particular versions we have to rely on there (due to upstream bugs)... But I'll read the article
