### ISSUE TITLE
README restructured text translation for PyPi distribution

### ISSUE THREAD

**Issue by miohtama** [CounterpartyXCP/counterpartyd#704]
For the package Python community adoption it is very important to have a proper README in place on PyPi.

PyPi website supports only Restructured Text format for READMEs currently. Python community wishes to support Markdown, but unfortunately we are not there yet.

Meantime it is possible to use the hack described below to transalte .md to .rst at the packaging.

If the authors are ok with this I can implement this to `setup.py`.

Or, simply, move from README.md to README.rst, as the text is not very long and thus has near-zero  restructured text syntax learning curve.

**Comment by adamkrellenstein** [comment]
ACK. I *guess* I'm OK with this. Personally, I kind of like having READMEs only in one place---in the source code (visible on GitHub), but I can be flexible here. (As long as it stays in Markdown!)

**Comment by ouziel-slama** [comment]
@miohtama, @adamkrellenstein, what do you think to use this: https://pypi.python.org/pypi/setuptools-markdown

**Comment by adamkrellenstein** [comment]
@ouziel-slama, looks good!

**Comment by ouziel-slama** [comment]
done [here](https://github.com/CounterpartyXCP/counterpartyd/commit/c9cc2929f761af3ff5ed6cf3ddf7943b12bbe19f) and [here](https://github.com/CounterpartyXCP/counterparty-cli/commit/9806a65b2806120e50e150e33b5a728846059cee)
