### ISSUE TITLE
More automatic release procedure

### ISSUE THREAD

**Issue by miohtama** [CounterpartyXCP/counterpartyd#705]
I has reading `release_procedure.md` and it looks quite long and error-prone list of manual tasks to perform.

Python community has come up with tools to automate the most of the steps described in the release procedure checklist.

For example, there exists `zest.releaser` tool to do 

* Changelog management

* Github tagging

* setup.py fiddling

* PyPi push

http://opensourcehacker.com/2012/08/14/high-quality-automated-package-releases-for-python-with-zest-releaser/

If the authors are open for cutting down the list of manual release procedure steps, I could see what I could here to help.

**Comment by adamkrellenstein** [comment]
I can't say this appeals to me much. Sounds like a solution in search of a problem. @ouziel-slama?

**Comment by ouziel-slama** [comment]
I agree. I'am really not convinced by the article.
