### ISSUE TITLE
Speed Up UTXO Search

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterpartyd#715]
* [ ] Batch RPC calls
* [x] btcd support

**Comment by karlkeefer** [comment]
Is this likely a bottleneck on `createSend` calls?

The time for those to complete seems to be hugely variable from ~2s to >20s in our usage, even on addresses with only a handful of txs.

**Comment by adamkrellenstein** [comment]
@karlkeefer, yep.

**Comment by adamkrellenstein** [comment]
Batch RPC calls done with #756
