### ISSUE TITLE
`Constructed transaction does not parse correctly`

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterpartyd#721]

**Comment by adamkrellenstein** [comment]
Sending dust to the destination helps?

**Comment by ouziel-slama** [comment]
see https://github.com/CounterpartyXCP/counterpartyd/pull/725

**Comment by adamkrellenstein** [comment]
Looking for an elegant fix to this.

**Comment by adamkrellenstein** [comment]
The problem commit? 
https://github.com/CounterpartyXCP/counterpartyd/commit/6e0bf7592d749728ce5e9e66691c4e6e73c19ae6

**Comment by ouziel-slama** [comment]
yep! the output used for the transaction can belongs to an 1 of X address that contains the monosig source address.

**Comment by adamkrellenstein** [comment]
Solved.
