### ISSUE TITLE
DEx orders not matched [$15]

### ISSUE THREAD

**Issue by rippler** [CounterpartyXCP/counterpartyd#729]
http://www.blockscan.com/orderInfo/11603913 - selling  0.00000001 OAZT for 0.0001 BTC
http://www.blockscan.com/orderInfo/11603912 - buying 0.00000001 OAZT for 0.0001 BTC
The two orders were placed at the same time, but didn't get matched.

**Comment by Jpja** [comment]
order.py:
547: tx0_price = util.price(tx0['get_quantity'], tx0['give_quantity'])
548: tx1_price = util.price(tx1['get_quantity'], tx1['give_quantity'])
549: tx1_inverse_price = util.price(tx1['give_quantity'], tx1['get_quantity'])

Could it be due to rounding in 'order.py' line 549?
Rounding up 'tx1_inverse_price' will fix it?

**Comment by Jpja** [comment]
If I understand the code directly, there's a 0.001 BTC minimum, hence your order of 0.0001 BTC is supposed not to match . See 'order.py', line 575:
min_btc_quantity = 0.001 * config.UNIT  # 0.001 BTC

Another case where orders are expected match, but don't, is when Counterwallet rounds the inputs. Example:
![fldc orderbook counterwallet](https://cloud.githubusercontent.com/assets/8447505/6678502/1ba086d0-cc44-11e4-9533-50c9e36d969d.PNG)

**Comment by rippler** [comment]
> If I understand the code directly, there's a 0.001 BTC minimum

Good point, so that'd be a case of input validation bug (another issue)?

**Comment by adamkrellenstein** [comment]
This doesn't look like a counterpartyd issue.

**Comment by ArtemKo7v** [comment]
>If I understand the code correctly, there's a 0.001 BTC minimum, hence your order of 0.0001 BTC is supposed not to match . See 'order.py', line 575:

Nonetheless, we made new orders with 0.001BTC volume, but they still did not matched.

http://www.blockscan.com/orderInfo/11611550
http://www.blockscan.com/orderInfo/11611552
http://www.blockscan.com/orderInfo/11611555

**Comment by Jpja** [comment]
```
 min_btc_quantity = 0.001 * config.UNIT  # 0.001 BTC
                if (forward_asset == config.BTC and forward_quantity <= min_btc_quantity) or (backward_asset == config.BTC and backward_quantity <= min_btc_quantity):
                    logger.debug('Skipping: below minimum {} quantity'.format(config.BTC))
```

Does an order with 0.00100001 BTC match?

**Comment by rippler** [comment]
Tried using 0.00101 BTC, orders matched (on testnet).
```
[INFO] Order: mkZ6ECVZYtTE6iGZ6wvBfkw49KLAvsGhCM ordered 1 GOLDBITCHEZ for 0.001
01 BTC in 5 blocks, with a provided fee of 0.0001 BTC and a required fee of 0.0
BTC (d887862c9cce0aa591b0a69d7dd0ba17cfa25d0b548997fd0ab32837a489b69f) [open]←[0
m
[INFO] Block: 328252 (3.92s)←[0m
[INFO] Order: mvBrgbMAucRUQJFJ4Ddjog6FvL4JDQtoPZ ordered 0.00101 BTC for 1 GOLDB
ITCHEZ in 5 blocks, with a provided fee of 0.0001 BTC and a required fee of 0.0
BTC (39168393ffbb7e49d7a38df8b6469e42175dc52fc3e38b02c702b4b84525e4ca) [open]←[0
m
[INFO] Order Match: 1 GOLDBITCHEZ for 0.00101 BTC (d887862c9cce0aa591b0a69d7dd0b
a17cfa25d0b548997fd0ab32837a489b69f_39168393ffbb7e49d7a38df8b6469e42175dc52fc3e3
8b02c702b4b84525e4ca) [pending]←[0m
[INFO] Block: 328253 (4.07s)←[0m
```
