### ISSUE TITLE
allow_unconfirmed_inputs: True does not appear to take effect.

### ISSUE THREAD

**Issue by cryptonaut420** [CounterpartyXCP/counterpartyd#757]
As per the slack channel..

Previously, when using V9.49.3, I was able to chain several dozen transactions together using unconfirmed inputs, which is what the FLDC and LTBCOIN projects rely on to be able to distribute coins out weekly/daily. Since upgrading to v9.51, this no longer appears to work and I just run into constant "Insufficient BTC (try using --unconfirmed)" errors, despite allow_unconfirmed_inputs being set to true. It will send one or two transactions, and then fail for the rest of the batch until those previous ones confirm, then it will send one or two more, and so on... you can see how that quickly makes things difficult when trying to send several hundred transactions. 

This is the payload defined in the script im using, which hasn't changed at all since it was working with 9.49.3 - other than replacing sign_raw and send_raw commands with signrawtransaction and sendrawtransaction in native bitcoind. 

```
payload = {                                                             
           "method": "create_send",                                            
           "params": {'source': source, 'destination': destination, 'asset': asset, 'quantity': int(quantity), 'fee': int(fee), 'allow_unconfirmed_inputs': True, 'regular_dust_size': int(sys.argv[2]), 'multisig_dust_size': int(sys.argv[2]), 'pubkey': sys.argv[3], 'encoding': 'multisig'},
           "jsonrpc": "2.0",                                                   
           "id": 0                                                             
       }
```

any ideas?

**Comment by ouziel-slama** [comment]
@cryptonaut420: hum.. I don't see any obvious reasons for your problem.. does the problem appears just after you restart the server or well after ?

**Comment by cryptonaut420** [comment]
@ouziel-slama I'm not sure what you mean. All I did was get rid of counterpartyd v9.49.3 and upgraded to 9.51, and then yeah did a server reboot. Since then allow_unconfirmed_inputs does not work.  Restarting the counterparty server doesnt do anything, the problem is persistant.

**Comment by cryptonaut420** [comment]
for reference, this is the script im using to generate the transactions: https://github.com/tokenly/tokenly-cms/blob/master/scripts/xcp-sendmany.py

basically it takes a CSV, loops through it and makes a transaction for each entry. command looks like "python xcp-sendmany.py <csv file> <dust output size to use, in satoshis> <source address pubkey>"

**Comment by deweller** [comment]
Are you running bitcoind with `addrindex=1` in the config?  And if you are, did you done a  `bitcoind -txindex -addrindex -reindex` operation at least once?

It sounds like maybe the txout search is not working in bitcoind.  And a missing or bad utxo index in bitcoind might explain that.

**Comment by cryptonaut420** [comment]
@deweller it's been running with addrindex=1 and txindex=1 since the last major update where it was required to install bitcoind with that patch. I will try reindexing anyways though see if that helps

**Comment by ouziel-slama** [comment]
@cryptonaut420 : I mean try to restart the server with the `--verbose` option and before making transactions, wait until you see the message 'Updating mempool.' (https://github.com/CounterpartyXCP/counterpartyd/blob/master/counterpartylib/lib/blocks.py#L1027). The idea is to wait that this loop https://github.com/CounterpartyXCP/counterpartyd/blob/master/counterpartylib/lib/blocks.py#L1044 finish to put in cache all unconfirmed transaction.
The PR https://github.com/CounterpartyXCP/counterpartyd/pull/756 fixes this problem.

**Comment by deweller** [comment]
@cryptonaut420, #760 has been merged into the develop branch.  Can you try that and see if it fixes this issue?

**Comment by cryptonaut420** [comment]
Alright, I finally have this working properly, yay!

Here's what I did:

* Tried doing the -reindex of the blockchain, which took forever. After that I started getting "could not read transaction from disk" errors in counterparty... I ended up redownloading the chain entirely, which got things back to normal.. so that was fun (and a waste of time lol).
* Tried the Verbose: true option, nothing really stood out other than it definitely was not seeing any available inputs (possibly incorrectly pruning them?)
* Tried installing the latest version (as of last night, so just the april 14th commits) of the ```develop``` branch, still had the same allow_unconfirmed_inputs issue though.
* @deweller had suggested maybe adding a small delay in between generating each transaction (possible funkyness going on with creating the transaction in the XCP API and sending it separately through the bitcoind API). That did not work either.
* Downloaded the latest version of develop again with the commits made earlier this morning... and it works like a charm!

So @ouziel-slama seems like something that you changed since yesterday (in commit 336185a?) solved the issue

**Comment by deweller** [comment]
@cryptonaut420 Are you running a51e89038029df509667ef076156c51b358f55e7 (the latest develop from this morning)?  If so, I'm guessing that #760 fixed this.

**Comment by cryptonaut420** [comment]
@deweller yep thats right

**Comment by adamkrellenstein** [comment]
Solved, it seems.
