### ISSUE TITLE
Output spent in mempool not taken into account

### ISSUE THREAD

**Issue by arhuaco** [CounterpartyXCP/counterpartyd#759]
I ran into a weird issue where sending an asset twice created the same raw transaction. The root cause is:

bitcoin-0.10.0/bin/bitcoin-cli searchrawtransactions ADDR

Returns outputs that are in the mempool, so they are (trying to be) spent but appear to be unspent to Counteparty.

Check this for an example: http://pastebin.com/ivLrnWcQ

I confirmed this happens both in testnet and regtest.

Why is this bad: It doesn't allow you to send more transactions until the current one is confirmed.

**Comment by deweller** [comment]
Could be related to #757

**Comment by adamkrellenstein** [comment]
Hm, interesting.

**Comment by adamkrellenstein** [comment]
I'm about to crash. @ouziel-slama, thoughts?

**Comment by arhuaco** [comment]
This hacky workaround fixes the issue for me: http://pastebin.com/G4Usp9u0

**Comment by ouziel-slama** [comment]
@arhuaco : nice catch!
@deweller : yeah I think it's related to #757 

Can you try please this patch: https://github.com/CounterpartyXCP/counterpartyd/pull/760

**Comment by arhuaco** [comment]
@ouziel-slama: I could not cherry-pick the patches from master/HEAD. Could you please post the patch sequence to cherry pick changes? (Probably including other changes).

I tried the develop branch but counterpartyd crashed. Here is the backtrace: http://pastebin.com/qGumU9nb

**Comment by ouziel-slama** [comment]
@arhuaco: seems you get an asset conservation error. Just catch up mainnet database with the develop branch and works well. Can you try to reparse the database and the restart the server: `counterparty-server reparse`.

**Comment by arhuaco** [comment]
I deleted the XCP database (rm .local/share/counterparty/counterparty.testnet.db) and it started parsing blocks (starting with block 100). But it crashed.

It seems there is a coinbase transaction to an address where I had previously sent XCP assets. I think this might be triggering the exception.

It crashed at block 117: http://pastebin.com/ycSWG5i7

Here is the block contents:

http://pastebin.com/Q7mbQFuY

**Comment by ouziel-slama** [comment]
hum.. really weird, for testnet the first block is 310000.. are you running regnet instead testnet ?

**Comment by arhuaco** [comment]
Yes, I'm running regtest. But if this happens here it can probably happen in testnet/mainnet. But then in testnet it would be harder to reproduce the exception because to get a coinbase transaction you would have to mine a block.

Unlikely but could happen. Shall I open a new issue for this?

I will start from scratch just to test that the issue that we are dealing with is solved, and keep this docker image in case we want to test again later.

I'll report back soon. Testing...

**Comment by ouziel-slama** [comment]
coinbase transactions are ignored and should not raise a bug (see here: https://github.com/CounterpartyXCP/counterpartyd/blob/develop/counterpartylib/lib/blocks.py#L549)...

**Comment by arhuaco** [comment]
I still see the issue: http://pastebin.com/8CtjJ3Ry

**Comment by arhuaco** [comment]
Branch "develop" worked in one of the testing environments, in the one I was using when I reported the issue. Maybe I did something wrong in the other test. I'll do it again and report back.

In any case, for it to work I had to apply this: http://pastebin.com/3N6gyzcn

The program crashes then the number of XCP held is 0 because held[asset] returns None.
I traced it after you told me that Coinbase TX was not the issue.

PS: There is a weird char after "issued" that cannot be encoded and makes Python crash. I deleted it in the fix I applied.

**Comment by ouziel-slama** [comment]
@arhuaco: fixed here https://github.com/CounterpartyXCP/counterpartyd/commit/88ef45146cfd25777ebdbc77cde8f3358c6f2a80
re-PS: check if your console is in UTF-8 (withe `locale` for instance)

**Comment by arhuaco** [comment]
I confirm develop works: http://pastebin.com/cMnLJQFB

PS:

Yeah, my locale was wrong. Running 'perl' was revealing: http://pastebin.com/wZjGkXrr
I wonder how I got this far with this (inside of a docker image, not many programs running, only Counterparty complained).

**Comment by ouziel-slama** [comment]
great! thanks for the feedback!

**Comment by adamkrellenstein** [comment]
Seems this was solved.
