### ISSUE TITLE
"Cannot Read Transaction from Disk"

### ISSUE THREAD

**Issue by cryptonaut420** [CounterpartyXCP/counterpartyd#761]
(*edit*: this is on the develop branch as of pull request #760)

this is sort of a follow up to issue #757 

I almost had things working with chaining together transactions... ran out of tokens on the address, so I filled it up with some more using the send command on the CLI. After that confirmed, tried running the script once more to push out some more transactions, but then got nothing but these errors all of a sudden:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/jsonrpc/manager.py", line 108, in _get_responses
    result = method(*request.args, **request.kwargs)
  File "/crypto/counterpartyd/counterpartylib/lib/api.py", line 449, in create_method
    return compose_transaction(db, name=tx, params=transaction_args, **common_args)
  File "/crypto/counterpartyd/counterpartylib/lib/api.py", line 313, in compose_transaction
    fee_provided=fee_provided)
  File "/crypto/counterpartyd/counterpartylib/lib/transaction.py", line 395, in construct
    unspent = backend.get_unspent_txouts(source, unconfirmed=allow_unconfirmed_inputs, multisig_inputs=multisig_inputs)
  File "/crypto/counterpartyd/counterpartylib/lib/backend/__init__.py", line 148, in get_unspent_txouts
    raw_transactions = searchrawtransactions(source, unconfirmed=True)
  File "/crypto/counterpartyd/counterpartylib/lib/backend/__init__.py", line 49, in searchrawtransactions
    return BACKEND().searchrawtransactions(address, unconfirmed=unconfirmed)
  File "/crypto/counterpartyd/counterpartylib/lib/backend/addrindex.py", line 140, in searchrawtransactions
    raise BackendRPCError(str(e))
counterpartylib.lib.backend.addrindex.BackendRPCError: {'code': -22, 'message': 'Cannot read transaction from disk'}

```

This is the transaction in question that seems to have caused it: https://blockchain.info/tx/d3a6adf910953d8251e187f67e7bf8246b0b1d67f9c323235785847dae9af622

Would this have something to do with the use of OP_RETURN? Seems like transactions were able to be chained together just fine with multisig encoding, but once I sent it a transaction that uses OP_RETURN instead, then the "cannot read transaction" errors started to show up. 

I had the same error yesterday as well after I did a reindex of the blockchain, not sure why exactly..  redownloading the blockchain seemed to fix it but I would rather not do that again.

ideas?

**Comment by deweller** [comment]
This is coming from bitcoind.  Here is the reference:

https://github.com/btcdrak/bitcoin/blob/addrindex/src/rpcrawtransaction.cpp#L150

**Comment by cryptonaut420** [comment]
seems like the TX index gets messed up somehow... but how I wonder? Really don't want to have to redownload or reindex to fix it, just for the same thing to happen again right after.

**Comment by adamkrellenstein** [comment]
Yeah, I don't think this is a Counterparty issue. (And a `reindex` should fix it, I expect.)

**Comment by rippler** [comment]
@deweller intrestingly that part of the code is part of the addrindex patch

**Comment by cryptonaut420** [comment]
@rippler do you think there could be an issue with the addrindex patch then (possibly when OP_RETURN is used, as I mentioned above..)? re-indexing is still in progress at the moment, not sure if that fixed anything yet

**Comment by rippler** [comment]
@cryptonaut420 I'm not qualified to judge and I don't have any indication that it's related, I just wanted to point that out that - if `reindex` doesn't help the patch may be worth another look (and then we could ask @btcdrak if he encountered something like that).

**Comment by cryptonaut420** [comment]
Looks like so far the reindex has worked and all is well now. I will keep an eye on it and see if it comes up again
